<?php
declare(strict_types=1);
require_once __DIR__ . '/config/bootstrap.php';
$db=Database::connection();
$ids=array_values(array_filter(array_map('intval',$_POST['ids']??[]),fn(int $id):bool=>$id>0));
if(!$ids){exit('<p style="font-family:Arial;padding:30px">Tidak ada soal yang dipilih.</p>');}
$placeholders=implode(',',array_fill(0,count($ids),'?'));
$stmt=$db->prepare("SELECT q.*,s.name subject_name,m.title material_title FROM questions q JOIN subjects s ON s.id=q.subject_id LEFT JOIN materials m ON m.id=q.material_id WHERE q.id IN ({$placeholders}) ORDER BY FIELD(q.id,{$placeholders})");
$stmt->execute(array_merge($ids,$ids));$questions=$stmt->fetchAll();
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><title>Cetak Soal</title><style>@page{size:A4;margin:18mm}body{font-family:Arial,sans-serif;color:#111;font-size:12pt;line-height:1.45}.toolbar{position:fixed;right:20px;top:18px}button{padding:9px 14px}.header{text-align:center;border-bottom:2px solid #111;padding-bottom:12px;margin-bottom:24px}.identity{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:20px 0}.question{margin:0 0 20px;page-break-inside:avoid}.options{display:grid;grid-template-columns:1fr 1fr;gap:6px 30px;margin:8px 0 0 18px}.answer-key{page-break-before:always}.answer-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.answer-item{border:1px solid #bbb;padding:8px;text-align:center}@media print{.toolbar{display:none}}</style></head><body><div class="toolbar"><button onclick="window.print()">Cetak</button></div><div class="header"><h2 style="margin:0 0 6px">LEMBAR SOAL PILIHAN GANDA</h2><div><?= e($questions[0]['subject_name']??'') ?></div></div><div class="identity"><div>Nama: __________________________</div><div>Kelas: __________________________</div><div>Tanggal: ________________________</div><div>Nilai: __________________________</div></div><p><strong>Petunjuk:</strong> Pilih satu jawaban yang paling tepat.</p><?php foreach($questions as $i=>$q): ?><div class="question"><div><strong><?= $i+1 ?>.</strong> <?= nl2br(e($q['question_text'])) ?></div><div class="options"><div>A. <?= e($q['option_a']) ?></div><div>B. <?= e($q['option_b']) ?></div><div>C. <?= e($q['option_c']) ?></div><div>D. <?= e($q['option_d']) ?></div></div></div><?php endforeach; ?><section class="answer-key"><h2>Kunci Jawaban</h2><div class="answer-grid"><?php foreach($questions as $i=>$q): ?><div class="answer-item"><?= $i+1 ?>. <strong><?= e($q['correct_option']) ?></strong></div><?php endforeach; ?></div></section></body></html>
