<?php
$edit = null;
if(isset($_GET['edit'])){$stmt=$db->prepare('SELECT * FROM subjects WHERE id=?');$stmt->execute([(int)$_GET['edit']]);$edit=$stmt->fetch();}
$showForm = isset($_GET['create']) || $edit;
$subjects = $db->query('SELECT s.*,(SELECT COUNT(*) FROM materials m WHERE m.subject_id=s.id) material_count,(SELECT COUNT(*) FROM questions q WHERE q.subject_id=s.id) question_count FROM subjects s ORDER BY s.status,s.name')->fetchAll();
?>
<div class="section-title"><div><h2>Daftar mata pelajaran</h2><p>Kelola kurikulum, jenjang, dan capaian pembelajaran.</p></div><a class="btn btn-primary" href="<?= url('subjects',['create'=>1]) ?>"><?= icon('plus',17) ?> Tambah</a></div>
<?php if($showForm): ?><section class="card mb-0"><div class="card-header"><div><h2><?= $edit?'Edit':'Tambah' ?> mata pelajaran</h2><p>Isi informasi utama mata pelajaran.</p></div></div><div class="card-body"><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_subject"><input type="hidden" name="id" value="<?= e($edit['id']??'') ?>"><div class="form-grid">
<div class="form-group"><label>Nama mata pelajaran *</label><input class="form-control" name="name" required value="<?= e($edit['name']??'') ?>"></div><div class="form-group"><label>Jenjang atau kelas *</label><input class="form-control" name="grade_level" required placeholder="Contoh: SMP Kelas VIII" value="<?= e($edit['grade_level']??'') ?>"></div>
<div class="form-group"><label>Semester</label><select class="form-control" name="semester"><option <?= selected($edit['semester']??'Ganjil','Ganjil') ?>>Ganjil</option><option <?= selected($edit['semester']??'','Genap') ?>>Genap</option></select></div><div class="form-group"><label>Tahun ajaran *</label><input class="form-control" name="academic_year" required placeholder="2026/2027" value="<?= e($edit['academic_year']??'2026/2027') ?>"></div>
<div class="form-group"><label>Kurikulum</label><input class="form-control" name="curriculum" value="<?= e($edit['curriculum']??'Kurikulum Merdeka') ?>"></div><div class="form-group"><label>Status</label><select class="form-control" name="status"><option value="active" <?= selected($edit['status']??'active','active') ?>>Aktif</option><option value="archived" <?= selected($edit['status']??'','archived') ?>>Arsip</option></select></div>
<div class="form-group full"><label>Deskripsi</label><textarea class="form-control" name="description"><?= e($edit['description']??'') ?></textarea></div><div class="form-group full"><label>Capaian pembelajaran</label><textarea class="form-control" name="learning_outcomes"><?= e($edit['learning_outcomes']??'') ?></textarea></div></div><div class="form-actions"><a class="btn btn-secondary" href="<?= url('subjects') ?>">Batal</a><button class="btn btn-primary" type="submit">Simpan mata pelajaran</button></div></form></div></section><?php endif; ?>
<section class="card mt-3"><div class="card-header"><div><h2>Semua mata pelajaran</h2><p><?= count($subjects) ?> data tersimpan</p></div><div class="search-box"><?= icon('search',17) ?><input class="form-control" placeholder="Cari mata pelajaran..." data-filter-table="#subject-table"></div></div><div class="table-wrap"><table class="data-table" id="subject-table"><thead><tr><th>Mata pelajaran</th><th>Periode</th><th>Materi</th><th>Soal</th><th>Status</th><th></th></tr></thead><tbody>
<?php foreach($subjects as $item): ?><tr><td><strong><?= e($item['name']) ?></strong><div class="muted text-sm"><?= e($item['grade_level']) ?> • <?= e($item['curriculum']) ?></div></td><td><?= e($item['semester']) ?><div class="muted text-sm"><?= e($item['academic_year']) ?></div></td><td><?= (int)$item['material_count'] ?></td><td><?= (int)$item['question_count'] ?></td><td><?= status_badge($item['status']) ?></td><td><div class="actions"><a class="btn btn-secondary btn-sm" href="<?= url('subjects',['edit'=>$item['id']]) ?>"><?= icon('edit',14) ?></a><form method="post" data-confirm="Hapus mata pelajaran ini? Data terkait dapat mencegah penghapusan."><?= csrf_field() ?><input type="hidden" name="action" value="delete_subject"><input type="hidden" name="id" value="<?= $item['id'] ?>"><button class="btn btn-danger btn-sm" type="submit"><?= icon('trash',14) ?></button></form></div></td></tr><?php endforeach; ?>
<?php if(!$subjects): ?><tr><td colspan="6"><div class="empty-state"><h3>Belum ada mata pelajaran</h3><p>Tambahkan mata pelajaran pertama untuk mulai menyusun kelas dan materi.</p></div></td></tr><?php endif; ?></tbody></table></div></section>
